# Generated by Django 5.0 on 2023-12-18 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_loja_produto_loja'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaDesejos',
        ),
    ]
