# Generated by Django 5.0 on 2023-12-18 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_delete_listadesejos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
