# Generated by Django 5.0 on 2024-01-22 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_carrinho_itemcarrinho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name_plural': 'Carrinhos de Compras'},
        ),
    ]
