# Generated by Django 5.0 on 2023-12-19 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_desejos', '0001_initial'),
        ('loja', '0005_delete_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadesejos',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='listadesejos',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='listadesejos',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ItemListaDesejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='lista_desejos.listadesejos')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
        ),
    ]
