# Generated by Django 5.0 on 2024-01-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_desejos', '0002_remove_listadesejos_produto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemlistadesejos',
            options={'verbose_name_plural': 'Itens da Lista de Desejos'},
        ),
        migrations.AlterModelOptions(
            name='listadesejos',
            options={'verbose_name_plural': 'Lista de Desejos'},
        ),
    ]
